-- 코드를 입력하세요
SELECT B.BOOK_ID, AUTHOR_NAME, TO_CHAR(published_date, 'YYYY-MM-DD') AS PUBLISHED_DATE
FROM BOOK B
INNER JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE B.CATEGORY = '경제'
ORDER BY PUBLISHED_DATE ASC